=== AlberRC/XMLyDTD1/Apartado2/validador.dtd
<!ELEMENT ligaBaloncesto (equipos+)>
<!ELEMENT equipos (jugadores)>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (nombre, apellidos, equipo, edad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT equipo (ciudad, presidente)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT presidente (nombrePresidente, apellidosPresidente)>
<!ELEMENT nombrePresidente (#PCDATA)>
<!ELEMENT apellidosPresidente (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== AlberRC/XMLyDTD1/Apartado2/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Alber Ruiz Clemente
Curso: DAW1
Fecha: 25-03-2025
Ejercicio: Ejercicio 2
-->
<!DOCTYPE ligaBaloncesto SYSTEM "validador.dtd">
<ligaBaloncesto>
    <equipos>
        <jugadores>
            <jugador>
                <nombre>LeBron</nombre>
                <apellidos>James</apellidos>
                <equipo>
                    <ciudad>Los Angeles</ciudad>
                    <presidente>
                        <nombrePresidente>Jeanie</nombrePresidente>
                        <apellidosPresidente>Buss</apellidosPresidente>
                    </presidente>
                </equipo>
                <edad>39</edad>
            </jugador>
            <jugador>
                <nombre>Anthony</nombre>
                <apellidos>Davis</apellidos>
                <equipo>
                    <ciudad>Los Angeles</ciudad>
                    <presidente>
                        <nombrePresidente>Jeanie</nombrePresidente>
                        <apellidosPresidente>Buss</apellidosPresidente>
                    </presidente>
                </equipo>
                <edad>31</edad>
            </jugador>
            <jugador>
                <nombre>D'Angelo</nombre>
                <apellidos>Russell</apellidos>
                <equipo>
                    <ciudad>Los Angeles</ciudad>
                    <presidente>
                        <nombrePresidente>Jeanie</nombrePresidente>
                        <apellidosPresidente>Buss</apellidosPresidente>
                    </presidente>
                </equipo>
                <edad>28</edad>
            </jugador>
        </jugadores>
    </equipos>
</ligaBaloncesto>
